name: build_cont
on: [push, pull_request]
jobs:
  build:
    name: Build on ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: [ 'ubuntu:18.04', 'ubuntu:20.04' ]
        # python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v3
    - name: run script
      run: bash ./scripts/build_on_docker.sh
