name: build_cont
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Build on ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['ubuntu:22.04']
        python-version: ['3.10']
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: bootstrap os
      run: |
        apt-get update --yes --quiet
        apt-get install --yes --quiet python3-openssl wget python3-setuptools
        wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1l-1ubuntu1.3_amd64.deb
        dpkg --install libssl1.1_1.1.1l-1ubuntu1.3_amd64.deb
        python -m ssl
    - name: bootstrap
      run: python -m pip install pydmt pymakehelper pyclassifiers setuptools
    - name: pydmt
      run: pydmt build --dev False
    - name: make
      run: pymakehelper run_make
